\input texinfo
@settitle escript

@c -----------------------------------------------------------------------------
@ifnottex
@node Top
@top Command reference

This manual is for escript documentation using the Tcl script language.
@end ifnottex

@menu
* Controls:: Control commands
* Image:: Image commands
* Layout:: Layout commands
* Size:: Size commands
* Margin:: Margin commands
* Align:: Alignment commands
* Index::  Complete index
@end menu

@c -----------------------------------------------------------------------------
@node Controls
@unnumbered Controls

@deffn Command button text
@strong{-id} @emph{identifier} @*
@strong{-size} @emph{size} @*
@strong{-icon} @emph{icon} @*
@strong{-icon_pos} @emph{icon_pos} @*
@strong{-body_color} @emph{body_color} @*
@end deffn

@deffn Command basic_thumb size
@strong{-id} @emph{identifier} @*
@strong{-color} @emph{color} @*
@end deffn

@deffn Command basic_track size
@strong{-id} @emph{identifier} @*
@strong{-color} @emph{color} @*
@strong{-vertical} @*
@end deffn

@deffn Command slider thumb track
@strong{-id} @emph{identifier} @*
@strong{-init_value} @emph{init_value} @*
@end deffn

@deffn Command slider_marks size subject
@strong{-id} @emph{identifier} @*
@strong{-num_divs} @emph{num_divs} @*
@strong{-major_divs} @emph{major_divs} @*
@end deffn

@deffn Command slider_labels size font_size labels subject
@strong{-id} @emph{identifier} @*
@end deffn

@c -----------------------------------------------------------------------------
@node Image
@unnumbered Image

@deffn Command image filename
@strong{-id} @emph{identifier} @*
@strong{-scale} @emph{scale} @*
@end deffn

@deffn Command gizmo filename
@strong{-id} @emph{identifier} @*
@strong{-scale} @emph{scale} @*
@end deffn

@deffn Command hgizmo filename
@strong{-id} @emph{identifier} @*
@strong{-scale} @emph{scale} @*
@end deffn

@deffn Command vgizmo filename
@strong{-id} @emph{identifier} @*
@strong{-scale} @emph{scale} @*
@end deffn

@deffn Command sprite filename height
@strong{-id} @emph{identifier} @*
@strong{-scale} @emph{scale} @*
@end deffn

@c -----------------------------------------------------------------------------
@node Layout
@unnumbered Layout

@deffn Command htile elements...
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command vtile elements...
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command layer elements...
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command deck elements...
@strong{-id} @emph{identifier} @*
@end deffn

@c -----------------------------------------------------------------------------
@node Size
@unnumbered Size

@deffn Command fixed_size size element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command hsize width element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command vsize width element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command hmin_size width element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command hmax_size width element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command min_size size element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command max_size size element
@strong{-id} @emph{identifier} @*
@end deffn

@c -----------------------------------------------------------------------------
@node Margin
@unnumbered Margin

@deffn Command left_margin left element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command top_margin top element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command right_margin right element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command bottom_margin bottom element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command xside_margin left_right element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command yside_margin top_bottom element
@strong{-id} @emph{identifier} @*
@end deffn

@c -----------------------------------------------------------------------------
@node Align
@unnumbered Align

@deffn Command halign align element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command align_left element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command align_center element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command align_right element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command valign align element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command align_top element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command align_middle element
@strong{-id} @emph{identifier} @*
@end deffn

@deffn Command align_bottom element
@strong{-id} @emph{identifier} @*
@end deffn

@c -----------------------------------------------------------------------------
@node Index
@unnumbered Index

@printindex fn

@c -----------------------------------------------------------------------------
@bye
